/**
 * TranscriptRepository — Phase 2 Wave 2.
 *
 * Ported from `legacy/python/src/database/repository.py:TranscriptRepository`.
 * One row per video (UNIQUE constraint on `transcripts.video_id`), so the
 * "create or replace" semantics are implemented as `DELETE` followed by
 * `INSERT`.
 *
 * CRITICAL atomicity invariant (audit-driven)
 * --------------------------------------------
 * v1's TS implementation issued the DELETE and the INSERT as two independent
 * `db.run` calls outside any transaction (`src-ts/database/repositories.ts`
 * lines 612-628). If the INSERT failed for any reason (constraint, I/O,
 * power loss), the DELETE had already committed — the row was destroyed and
 * no replacement landed. v2 forecloses this entire class of bug by performing
 * BOTH statements inside ONE `withTransaction` callback. better-sqlite3
 * wraps the closure in `BEGIN ... COMMIT` and rolls back on throw, so the
 * delete and the insert either both land or neither do.
 *
 * Reads parse through `TranscriptRowSchema` before returning, so the public
 * surface only ever hands a Zod-validated shape to callers. Mismatched
 * column types fail loudly at the boundary instead of silently downstream.
 */

import type { Database } from 'better-sqlite3';

import { DatabaseError } from '../errors/index.js';
import { TranscriptRowSchema, type TranscriptRow } from '../schemas/db.js';
import { type VideoId } from '../types/branded.js';
import logger from '../utils/logger.js';
import type { DatabaseManager } from './connection.js';

/**
 * Caller-facing input shape for `upsert`. Mirrors the Python
 * `transcript_data: Dict` parameter but typed.
 *
 * `segments` is the structured transcript payload as it arrives from the
 * extractor (an array of `{ text, start, duration }` objects, etc.). The
 * repository serialises it to JSON before persisting so the table column
 * stays a TEXT blob.
 */
export interface TranscriptInput {
  /** ISO 639-1 language code. Defaults to `'en'` when omitted. */
  readonly language?: string;
  /** Concatenated transcript text. Required. */
  readonly fullText: string;
  /** Segments array, persisted as JSON string. Defaults to `[]`. */
  readonly segments?: ReadonlyArray<unknown>;
  /**
   * `true` when YouTube auto-generated the captions, `false` when human-
   * authored. Defaults to `true` (matches Python default).
   */
  readonly isAutoGenerated?: boolean;
}

/**
 * Row shape returned to callers — same as `TranscriptRow` from the Zod
 * schema, re-exported here as the canonical repository return type.
 */
export type Transcript = TranscriptRow;

export class TranscriptRepository {
  constructor(private readonly dbManager: DatabaseManager) {}

  /**
   * Atomic create-or-replace. Deletes any existing transcript row for
   * `videoId`, then inserts the new one — both inside ONE `withTransaction`
   * callback. If the INSERT throws, the DELETE rolls back with it; the
   * original row remains.
   *
   * @param videoId - Branded YouTube video ID. The DB column has a
   *                  `REFERENCES videos(video_id)` FK; the referenced
   *                  `videos` row must already exist.
   * @param transcript - New transcript payload.
   * @returns The persisted transcript row, parsed through `TranscriptRowSchema`.
   * @throws {DatabaseError} If the transaction rolls back. The original
   *                        cause is preserved on `error.cause`.
   */
  upsert(videoId: VideoId, transcript: TranscriptInput): Transcript {
    const language = transcript.language ?? 'en';
    const fullText = transcript.fullText;
    const segmentsJson = JSON.stringify(transcript.segments ?? []);
    const isAutoGenerated = (transcript.isAutoGenerated ?? true) ? 1 : 0;

    try {
      const inserted = this.dbManager.withTransaction((db: Database): TranscriptRow => {
        // Delete existing (idempotent — no-op if absent)
        db.prepare('DELETE FROM transcripts WHERE video_id = ?').run(videoId);

        // Insert new
        db.prepare(
          `INSERT INTO transcripts (video_id, language, full_text, segments_json, is_auto_generated)
           VALUES (?, ?, ?, ?, ?)`
        ).run(videoId, language, fullText, segmentsJson, isAutoGenerated);

        // Read-back inside the same transaction so the return value is
        // the actually-persisted row, not a reconstruction.
        const row = db.prepare('SELECT * FROM transcripts WHERE video_id = ?').get(videoId);

        if (row === undefined) {
          // Should be impossible — the INSERT immediately above must
          // have produced exactly one matching row. Defensive throw so
          // the transaction rolls back and the caller sees a typed
          // error rather than a silent inconsistency.
          throw new DatabaseError('Inserted transcript not found on read-back', {
            operation: 'upsert',
            table: 'transcripts',
            context: { videoId },
          });
        }

        return TranscriptRowSchema.parse(row);
      });

      logger.info({ videoId }, 'transcript upserted');
      return inserted;
    } catch (error) {
      if (error instanceof DatabaseError) {
        throw error;
      }
      throw new DatabaseError('Failed to upsert transcript', {
        operation: 'upsert',
        table: 'transcripts',
        cause: error,
        context: { videoId },
      });
    }
  }

  /**
   * Read the transcript for a video. Returns `undefined` when no row
   * exists. Returned rows are parsed through `TranscriptRowSchema`.
   */
  findByVideoId(videoId: VideoId): Transcript | undefined {
    try {
      const row = this.dbManager
        .prepare<readonly [string], unknown>('SELECT * FROM transcripts WHERE video_id = ?')
        .get(videoId);

      if (row === undefined) {
        return undefined;
      }

      return TranscriptRowSchema.parse(row);
    } catch (error) {
      if (error instanceof DatabaseError) {
        throw error;
      }
      throw new DatabaseError('Failed to find transcript by video id', {
        operation: 'findByVideoId',
        table: 'transcripts',
        cause: error,
        context: { videoId },
      });
    }
  }

  /**
   * Whether a transcript row exists for `videoId`. Used by the extractor
   * to decide whether to call the Whisper fallback.
   */
  exists(videoId: VideoId): boolean {
    try {
      const result = this.dbManager
        .prepare<
          readonly [string],
          { c: number }
        >('SELECT COUNT(*) AS c FROM transcripts WHERE video_id = ?')
        .get(videoId);

      return (result?.c ?? 0) > 0;
    } catch (error) {
      if (error instanceof DatabaseError) {
        throw error;
      }
      throw new DatabaseError('Failed to check transcript existence', {
        operation: 'exists',
        table: 'transcripts',
        cause: error,
        context: { videoId },
      });
    }
  }

  /**
   * Delete the transcript for a video. Idempotent — returns the number of
   * rows affected (0 or 1). Wrapped in `withTransaction` for consistency
   * with the upsert path; even single-statement writes go through the
   * transaction discipline.
   */
  deleteByVideoId(videoId: VideoId): number {
    try {
      return this.dbManager.withTransaction((db: Database): number => {
        const info = db.prepare('DELETE FROM transcripts WHERE video_id = ?').run(videoId);
        return Number(info.changes);
      });
    } catch (error) {
      if (error instanceof DatabaseError) {
        throw error;
      }
      throw new DatabaseError('Failed to delete transcript', {
        operation: 'deleteByVideoId',
        table: 'transcripts',
        cause: error,
        context: { videoId },
      });
    }
  }

  /**
   * Count of transcript rows in the table. Used by report aggregation
   * paths (`html_generator.py:289` walks every video and asks "has a
   * transcript?"; a direct COUNT is cheaper when only the total matters).
   */
  count(): number {
    try {
      const row = this.dbManager
        .prepare<readonly [], { c: number }>('SELECT COUNT(*) AS c FROM transcripts')
        .get();
      return row?.c ?? 0;
    } catch (error) {
      if (error instanceof DatabaseError) {
        throw error;
      }
      throw new DatabaseError('Failed to count transcripts', {
        operation: 'count',
        table: 'transcripts',
        cause: error,
      });
    }
  }
}
