/**
 * Transcript extraction using `youtube-transcript`.
 *
 * Lifted from `src-ts/extractors/TranscriptExtractor.ts` (v1) per PORT_PLAN
 * Wave 3. Minor v2 fixes applied:
 *
 *   - **Language no longer hardcoded.** v1 always reported
 *     `language: 'en', is_auto_generated: true` regardless of which
 *     language was actually requested or returned. v2 reads the per-segment
 *     `lang` field that the `youtube-transcript` library exposes (when
 *     present) and falls back to the requested language. The
 *     `is_auto_generated` flag is configurable via `assumeAutoGenerated`
 *     (default `true` — matches v1 behaviour for callers that haven't
 *     opted in to the new option).
 *   - **No `any` types.** v1's `whisperExtractor: any` typed slot is now a
 *     `WhisperLike` structural interface — the only method the extractor
 *     calls on it is `extract(videoId)`, so the contract is narrow and
 *     explicit.
 *
 * Everything else is identical to v1: rate limit + exponential backoff,
 * graceful Whisper fallback, batch extraction with per-video isolation.
 */

import { YoutubeTranscript, type TranscriptResponse } from 'youtube-transcript';

import { ValidationError } from '../errors/index.js';
import type { VideoId } from '../types/index.js';
import logger from '../utils/logger.js';

/**
 * Transcript segment with start/duration in seconds.
 */
export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

/**
 * Extracted transcript data — the shared shape between YouTube-API and
 * Whisper-subprocess paths.
 */
export interface TranscriptData {
  full_text: string;
  segments: TranscriptSegment[];
  language: string;
  is_auto_generated: boolean;
  from_whisper?: boolean;
}

/**
 * Structural contract a `whisperExtractor` instance must satisfy. The only
 * method TranscriptExtractor calls is `extract`. Both the v2
 * `WhisperExtractor` and any test double implementing the same method are
 * accepted by this type.
 *
 * `videoId` is the v2-branded `VideoId` at the module boundary
 * (invariant #3). The brand is structurally a string, so existing
 * implementations that declare `videoId: string` continue to satisfy
 * this interface — but new callers are forced through the validator.
 */
export interface WhisperLike {
  extract(videoId: VideoId): Promise<TranscriptData | null>;
}

/**
 * Options for constructing a TranscriptExtractor.
 */
export interface TranscriptExtractorOptions {
  /**
   * Preferred languages, in priority order. The first entry is the one
   * requested from the YouTube API. Defaults to `['en', 'en-GB', 'en-US']`.
   */
  languages?: string[];
  /** Minimum delay between requests in ms. Default 2000. */
  rateLimitDelay?: number;
  /** Optional Whisper-shaped fallback. */
  whisperExtractor?: WhisperLike;
  /**
   * Default `is_auto_generated` flag when the upstream library doesn't
   * supply it. The `youtube-transcript` package does not distinguish
   * manual vs auto-generated tracks; YouTube-side it would be the "a."
   * prefix on the track id, but we never see that here. Default `true`
   * (matches v1 behaviour — most YouTube tracks are auto-generated).
   */
  assumeAutoGenerated?: boolean;
}

/**
 * Extract YouTube transcripts with rate limiting, retry, and optional
 * Whisper fallback.
 */
export class TranscriptExtractor {
  private readonly languages: string[];
  private readonly rateLimitDelay: number;
  private lastRequestTime: number;
  private readonly whisperExtractor: WhisperLike | undefined;
  private readonly assumeAutoGenerated: boolean;

  constructor(options: TranscriptExtractorOptions = {}) {
    this.languages = options.languages ?? ['en', 'en-GB', 'en-US'];
    this.rateLimitDelay = options.rateLimitDelay ?? 2000;
    this.lastRequestTime = 0;
    this.whisperExtractor = options.whisperExtractor;
    this.assumeAutoGenerated = options.assumeAutoGenerated ?? true;

    logger.info(
      {
        languages: this.languages,
        rateLimitDelay: this.rateLimitDelay,
        hasWhisperFallback: this.whisperExtractor !== undefined,
        assumeAutoGenerated: this.assumeAutoGenerated,
      },
      'TranscriptExtractor initialized'
    );
  }

  /**
   * Extract transcript for a video. Tries the YouTube API first with
   * exponential backoff on rate-limit, then optionally falls back to
   * Whisper.
   *
   * @param videoId - Branded YouTube video ID (`VideoId`). The brand is
   *                  structurally a string and the runtime validators
   *                  below preserve v1 input safety for callers that
   *                  cast in.
   * @param maxRetries - Max retries on rate-limit. Default 3.
   * @param useWhisperFallback - Whether to try Whisper if YouTube fails.
   *                              Default `true`.
   * @returns Transcript data or `null` if neither source produced one.
   * @throws {ValidationError} If videoId is missing or malformed.
   */
  async extract(
    videoId: VideoId,
    maxRetries = 3,
    useWhisperFallback = true
  ): Promise<TranscriptData | null> {
    // Boundary validation. The same regex `asVideoId` uses is enforced
    // here so callers that haven't branded their input upstream still get
    // a clear failure. The `VideoId` brand is compile-time only — at
    // runtime any string can be cast in, so we validate defensively.
    if (typeof videoId !== 'string' || !videoId.trim()) {
      throw new ValidationError('videoId must be a non-empty string', {
        field: 'videoId',
        value: videoId,
      });
    }

    if (!/^[A-Za-z0-9_-]{11}$/.test(videoId)) {
      throw new ValidationError('Invalid YouTube video ID format', {
        field: 'videoId',
        value: videoId,
      });
    }

    await this.waitForRateLimit();

    let retryCount = 0;
    let youtubeFailedReason: string | null = null;

    while (retryCount <= maxRetries) {
      try {
        const transcriptData = await this.extractTranscript(videoId);
        if (transcriptData !== null) {
          logger.info(
            {
              videoId,
              language: transcriptData.language,
              segmentCount: transcriptData.segments.length,
            },
            'Successfully extracted YouTube transcript'
          );
          return transcriptData;
        }
        youtubeFailedReason = 'No transcript available';
        break;
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);

        if (errorMessage.toLowerCase().includes('rate limit')) {
          retryCount++;
          if (retryCount <= maxRetries) {
            const waitTime = this.rateLimitDelay * Math.pow(2, retryCount);
            logger.warn(
              { videoId, retryCount, maxRetries, waitTime },
              'Rate limited - applying exponential backoff'
            );
            await this.sleep(waitTime);
          } else {
            youtubeFailedReason = 'Rate limit exceeded';
            logger.error(
              { videoId, retries: retryCount },
              'YouTube transcript unavailable (rate limit)'
            );
            break;
          }
        } else {
          youtubeFailedReason = errorMessage;
          logger.debug({ videoId, error: errorMessage }, 'YouTube transcript extraction failed');
          break;
        }
      }
    }

    // Whisper fallback path
    if (youtubeFailedReason !== null) {
      if (useWhisperFallback && this.whisperExtractor !== undefined) {
        try {
          logger.info({ videoId }, 'Trying Whisper fallback');
          const whisperTranscript = await this.whisperExtractor.extract(videoId);
          if (whisperTranscript !== null) {
            logger.info({ videoId }, 'Successfully extracted Whisper transcript');
            return whisperTranscript;
          }
          logger.warn({ videoId }, 'Whisper transcription failed');
        } catch (error) {
          const errorMessage =
            error instanceof Error ? error.message.split('\n')[0].substring(0, 100) : String(error);
          logger.error({ videoId, error: errorMessage }, 'Whisper extraction error');
        }
      } else {
        logger.info({ videoId, reason: youtubeFailedReason }, 'No transcript available');
      }
    }

    return null;
  }

  /**
   * Inner fetch + convert. Separated so the retry loop in `extract` can
   * intercept rate-limit errors cleanly.
   *
   * Iterates the configured language priority list — a video that only
   * carries `en-GB` captions (with `en` returning "No transcript") now
   * surfaces those captions instead of falling straight through to
   * Whisper. Rate-limit and "video unavailable" errors short-circuit
   * the loop with the same semantics as v1 — they're not "missing
   * captions" failures, they're transport / target failures.
   */
  private async extractTranscript(videoId: VideoId): Promise<TranscriptData | null> {
    // Treat these substrings as "this language has no captions; try
    // the next one" rather than as a terminal failure. Anything else
    // is propagated (rate-limit) or short-circuits (video unavailable).
    const missingPatterns = ['Transcript is disabled', 'No transcript'];

    for (const lang of this.languages) {
      try {
        const transcript = await YoutubeTranscript.fetchTranscript(videoId, { lang });

        if (transcript.length === 0) {
          // Empty for this language — try the next.
          logger.debug({ videoId, lang }, 'Empty transcript; trying next language');
          continue;
        }

        const segments: TranscriptSegment[] = transcript.map((segment: TranscriptResponse) => ({
          start: segment.offset / 1000,
          duration: segment.duration / 1000,
          text: segment.text,
        }));

        const fullText = segments.map((seg) => seg.text).join(' ');

        // Language detection: prefer the per-segment lang the library
        // returns; fall back to the language we actually requested
        // (not languages[0]) so the recorded language matches the
        // track we got back. v1 always wrote `'en'`.
        const detectedLanguage = transcript[0]?.lang ?? lang;

        return {
          full_text: fullText,
          segments,
          language: detectedLanguage,
          is_auto_generated: this.assumeAutoGenerated,
        };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);

        // Rate-limit errors are transport-level — bubble to the outer
        // retry handler regardless of language.
        if (errorMessage.toLowerCase().includes('rate limit')) {
          throw error;
        }

        // Video unavailable applies to the target, not the language —
        // no point in trying other languages.
        if (errorMessage.includes('Video unavailable')) {
          logger.warn({ videoId }, 'Video unavailable');
          return null;
        }

        // "Missing for this language" — fall through to the next entry.
        if (missingPatterns.some((p) => errorMessage.includes(p))) {
          logger.debug({ videoId, lang }, 'No transcript for requested language; trying next');
          continue;
        }

        // Anything else: log + try the next language. Mirrors v1 which
        // returned null on unknown errors — but per-language so a single
        // odd error doesn't blank out the whole priority list.
        const errorType = error instanceof Error ? error.constructor.name : 'Error';
        logger.debug(
          { videoId, lang, errorType, message: errorMessage.substring(0, 80) },
          'Transcript extraction error; trying next language'
        );
      }
    }

    // Exhausted every configured language without a hit.
    logger.debug(
      { videoId, languages: this.languages },
      'No transcript available in any configured language'
    );
    return null;
  }

  /**
   * Extract transcripts for a list of videos. One failure does not cause
   * the rest to fail — each entry's result is independent.
   *
   * `VideoId[]` at the boundary (invariant #3). The brand is structurally
   * a string, so the runtime keys of the returned record are still bare
   * video-id strings.
   */
  async extractBatch(videoIds: VideoId[]): Promise<Record<string, TranscriptData | null>> {
    if (!Array.isArray(videoIds)) {
      throw new ValidationError('videoIds must be an array', {
        field: 'videoIds',
        value: videoIds,
      });
    }

    const results: Record<string, TranscriptData | null> = {};

    for (const videoId of videoIds) {
      try {
        results[videoId] = await this.extract(videoId);
      } catch (error) {
        logger.error(
          {
            videoId,
            error: error instanceof Error ? error.message : String(error),
          },
          'Failed to extract transcript in batch'
        );
        results[videoId] = null;
      }
    }

    return results;
  }

  /**
   * Sleep until the rate-limit window has elapsed since the last request.
   */
  private async waitForRateLimit(): Promise<void> {
    const currentTime = Date.now();
    const timeSinceLast = currentTime - this.lastRequestTime;

    if (timeSinceLast < this.rateLimitDelay) {
      const waitTime = this.rateLimitDelay - timeSinceLast;
      logger.debug({ waitTime }, 'Rate limit delay');
      await this.sleep(waitTime);
    }

    this.lastRequestTime = Date.now();
  }

  /**
   * Generic sleep helper.
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  /**
   * Format a transcript with `[MM:SS]` or `[HH:MM:SS]` prefixes.
   */
  formatTranscriptWithTimestamps(transcriptData: TranscriptData | null): string {
    if (transcriptData === null || transcriptData.segments.length === 0) {
      return '';
    }

    const formattedLines: string[] = [];
    for (const segment of transcriptData.segments) {
      const timestamp = this.formatTimestamp(segment.start);
      const text = segment.text.trim();
      formattedLines.push(`[${timestamp}] ${text}`);
    }

    return formattedLines.join('\n');
  }

  /**
   * Format seconds as `MM:SS` or `HH:MM:SS`.
   */
  private formatTimestamp(seconds: number): string {
    const totalSeconds = Math.floor(seconds);
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor((totalSeconds % 3600) / 60);
    const secs = totalSeconds % 60;

    if (hours > 0) {
      return `${hours.toString().padStart(2, '0')}:${minutes
        .toString()
        .padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }

  /**
   * Build a YouTube URL with a `?t=Xs` deep link.
   */
  generateYouTubeTimestampUrl(videoId: string, seconds: number): string {
    const timestampSeconds = Math.floor(seconds);
    return `https://youtube.com/watch?v=${videoId}&t=${timestampSeconds}s`;
  }

  /**
   * Word/char/segment/duration stats for a transcript.
   */
  getTranscriptStats(transcriptData: TranscriptData | null): {
    word_count: number;
    char_count: number;
    segment_count: number;
    duration_seconds: number;
    language: string;
    is_auto_generated: boolean;
  } {
    if (transcriptData === null) {
      return {
        word_count: 0,
        char_count: 0,
        segment_count: 0,
        duration_seconds: 0,
        language: 'unknown',
        is_auto_generated: true,
      };
    }

    const fullText = transcriptData.full_text;
    const segments = transcriptData.segments;

    const wordCount = fullText.split(/\s+/).filter((w) => w.length > 0).length;
    const charCount = fullText.length;
    const segmentCount = segments.length;

    let durationSeconds = 0;
    if (segments.length > 0) {
      const lastSegment = segments[segments.length - 1];
      durationSeconds = lastSegment.start + lastSegment.duration;
    }

    return {
      word_count: wordCount,
      char_count: charCount,
      segment_count: segmentCount,
      duration_seconds: Math.floor(durationSeconds),
      language: transcriptData.language || 'unknown',
      is_auto_generated: transcriptData.is_auto_generated,
    };
  }
}
