/**
 * Wave 3 TranscriptExtractor tests.
 *
 * Ported from `src-ts/extractors/__tests__/TranscriptExtractor.test.ts` (v1).
 * Behavioural parity with v1, plus two v2-only properties:
 *
 *   1. Language detection honours the per-segment `lang` field from
 *      `youtube-transcript` when present, rather than hardcoding `'en'`.
 *   2. `assumeAutoGenerated` is respected when the upstream library does
 *      not distinguish auto vs manual tracks.
 *
 * No `any` casts — `as unknown as ...` is used to construct deliberately
 * shape-broken inputs.
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';

import { TranscriptExtractor, type WhisperLike } from '../extractors/TranscriptExtractor.js';
import { ValidationError } from '../errors/index.js';
import { asVideoId, type VideoId } from '../types/index.js';

const VIDEO_A = asVideoId('dQw4w9WgXcQ');
const VIDEO_B = asVideoId('jNQXAC9IVRw');

// Mock the youtube-transcript module before any imports of TranscriptExtractor
vi.mock('youtube-transcript', () => ({
  YoutubeTranscript: {
    fetchTranscript: vi.fn(),
  },
}));

// Acquire the mocked function through the module surface
import { YoutubeTranscript } from 'youtube-transcript';
const mockFetchTranscript = YoutubeTranscript.fetchTranscript as ReturnType<typeof vi.fn>;

describe('TranscriptExtractor', () => {
  let extractor: TranscriptExtractor;

  beforeEach(() => {
    vi.clearAllMocks();
    mockFetchTranscript.mockReset();

    extractor = new TranscriptExtractor({
      languages: ['en'],
      rateLimitDelay: 10,
    });
  });

  describe('constructor', () => {
    it('creates an extractor with default options', () => {
      // Arrange + Act
      const defaultExtractor = new TranscriptExtractor();
      // Assert
      expect(defaultExtractor).toBeInstanceOf(TranscriptExtractor);
    });

    it('accepts custom languages and rate limit', () => {
      // Arrange + Act
      const custom = new TranscriptExtractor({
        languages: ['en', 'es'],
        rateLimitDelay: 5000,
      });
      // Assert
      expect(custom).toBeInstanceOf(TranscriptExtractor);
    });

    it('accepts a structurally-typed whisper extractor', () => {
      // Arrange
      const whisper: WhisperLike = {
        extract: vi.fn(),
      };

      // Act
      const e = new TranscriptExtractor({ whisperExtractor: whisper });

      // Assert
      expect(e).toBeInstanceOf(TranscriptExtractor);
    });
  });

  describe('extract', () => {
    it('extracts a transcript and joins segments into full_text', async () => {
      // Arrange
      mockFetchTranscript.mockResolvedValue([
        { offset: 0, duration: 2000, text: 'Hello world' },
        { offset: 2000, duration: 3000, text: 'This is a test' },
      ]);

      // Act
      const result = await extractor.extract(VIDEO_A);

      // Assert
      expect(result).not.toBeNull();
      expect(result?.full_text).toBe('Hello world This is a test');
      expect(result?.segments).toHaveLength(2);
      expect(result?.segments[0]).toEqual({
        start: 0,
        duration: 2,
        text: 'Hello world',
      });
      expect(result?.language).toBe('en');
      expect(result?.is_auto_generated).toBe(true);
    });

    it('detects language from the per-segment lang field when present', async () => {
      // Arrange — v1 hardcoded 'en'; v2 must reflect what the library returned
      mockFetchTranscript.mockResolvedValue([
        { offset: 0, duration: 1000, text: 'Bonjour', lang: 'fr' },
      ]);

      // Act
      const result = await extractor.extract(VIDEO_A);

      // Assert
      expect(result?.language).toBe('fr');
    });

    it('iterates configured language priority list until one succeeds', async () => {
      // Arrange — extractor configured with `en` then `en-GB`. The first
      // language fails with "No transcript"; the second returns content.
      // v1 always requested `languages[0]` and gave up — this test pins
      // the v2 fallback behaviour.
      const multiLang = new TranscriptExtractor({
        languages: ['en', 'en-GB'],
        rateLimitDelay: 10,
      });
      mockFetchTranscript
        .mockRejectedValueOnce(new Error('No transcript for en'))
        .mockResolvedValueOnce([{ offset: 0, duration: 1000, text: 'British captions' }]);

      // Act
      const result = await multiLang.extract(VIDEO_A);

      // Assert — the requested `en-GB` is recorded as the language
      // (no per-segment lang in the mock; falls back to the requested).
      expect(result).not.toBeNull();
      expect(result?.language).toBe('en-GB');
      expect(mockFetchTranscript).toHaveBeenCalledTimes(2);
      expect(mockFetchTranscript).toHaveBeenNthCalledWith(1, VIDEO_A, { lang: 'en' });
      expect(mockFetchTranscript).toHaveBeenNthCalledWith(2, VIDEO_A, {
        lang: 'en-GB',
      });
    });

    it('returns null only after every configured language fails', async () => {
      // Arrange — both languages report "No transcript".
      const multiLang = new TranscriptExtractor({
        languages: ['en', 'en-GB'],
        rateLimitDelay: 10,
      });
      mockFetchTranscript.mockRejectedValue(new Error('No transcript'));

      // Act
      const result = await multiLang.extract(VIDEO_A);

      // Assert
      expect(result).toBeNull();
      // Per-language attempts; only one outer rate-limit iteration because
      // the failure isn't classified as rate-limit.
      expect(mockFetchTranscript).toHaveBeenCalledTimes(2);
    });

    it('honours assumeAutoGenerated=false when configured', async () => {
      // Arrange
      const e = new TranscriptExtractor({
        languages: ['en'],
        rateLimitDelay: 10,
        assumeAutoGenerated: false,
      });
      mockFetchTranscript.mockResolvedValue([{ offset: 0, duration: 1000, text: 'manual track' }]);

      // Act
      const result = await e.extract(VIDEO_A);

      // Assert
      expect(result?.is_auto_generated).toBe(false);
    });

    it('returns null on an empty transcript array', async () => {
      // Arrange
      mockFetchTranscript.mockResolvedValue([]);

      // Act
      const result = await extractor.extract(VIDEO_A);

      // Assert
      expect(result).toBeNull();
    });

    it('returns null when YouTube reports the transcript is disabled', async () => {
      // Arrange
      mockFetchTranscript.mockRejectedValue(new Error('Transcript is disabled on this video'));

      // Act + Assert
      expect(await extractor.extract(VIDEO_A)).toBeNull();
    });

    it('returns null when the video is unavailable', async () => {
      // Arrange
      mockFetchTranscript.mockRejectedValue(new Error('Video unavailable'));

      // Act + Assert
      expect(await extractor.extract(VIDEO_A)).toBeNull();
    });

    it('throws ValidationError on empty input', async () => {
      // Arrange — deliberately shape-broken; the brand is compile-time only.
      const bad = '' as unknown as VideoId;
      // Act + Assert
      await expect(extractor.extract(bad)).rejects.toThrow(ValidationError);
    });

    it('throws ValidationError on non-string input', async () => {
      // Arrange — deliberately shape-broken; cast through unknown.
      const bad = 123 as unknown as VideoId;
      // Act + Assert
      await expect(extractor.extract(bad)).rejects.toThrow(ValidationError);
    });

    it('throws ValidationError on a malformed video ID', async () => {
      // Arrange — deliberately shape-broken; the runtime validator catches.
      const bad = 'not-an-id' as unknown as VideoId;
      // Act + Assert
      await expect(extractor.extract(bad)).rejects.toThrow(ValidationError);
    });

    it('retries on rate-limit errors with exponential backoff', async () => {
      // Arrange
      let attempt = 0;
      mockFetchTranscript.mockImplementation(() => {
        attempt++;
        if (attempt <= 2) {
          return Promise.reject(new Error('Rate limit exceeded'));
        }
        return Promise.resolve([{ offset: 0, duration: 1000, text: 'OK' }]);
      });

      // Act
      const result = await extractor.extract(VIDEO_A, 3);

      // Assert
      expect(result).not.toBeNull();
      expect(attempt).toBe(3);
    });

    it('returns null after exhausting rate-limit retries', async () => {
      // Arrange
      mockFetchTranscript.mockRejectedValue(new Error('Rate limit exceeded'));

      // Act
      const result = await extractor.extract(VIDEO_A, 2);

      // Assert
      expect(result).toBeNull();
      expect(mockFetchTranscript).toHaveBeenCalledTimes(3); // initial + 2 retries
    });

    it('falls back to Whisper when YouTube fails and a fallback is configured', async () => {
      // Arrange
      const whisper: WhisperLike = {
        extract: vi.fn().mockResolvedValue({
          full_text: 'Whisper transcript',
          segments: [{ start: 0, duration: 1, text: 'Whisper transcript' }],
          language: 'en',
          is_auto_generated: false,
          from_whisper: true,
        }),
      };
      const e = new TranscriptExtractor({
        whisperExtractor: whisper,
        rateLimitDelay: 10,
      });
      mockFetchTranscript.mockRejectedValue(new Error('No transcript'));

      // Act
      const result = await e.extract(VIDEO_A);

      // Assert
      expect(result?.from_whisper).toBe(true);
      expect(whisper.extract).toHaveBeenCalledWith('dQw4w9WgXcQ');
    });

    it('returns null when Whisper also fails', async () => {
      // Arrange
      const whisper: WhisperLike = {
        extract: vi.fn().mockResolvedValue(null),
      };
      const e = new TranscriptExtractor({
        whisperExtractor: whisper,
        rateLimitDelay: 10,
      });
      mockFetchTranscript.mockRejectedValue(new Error('No transcript'));

      // Act + Assert
      expect(await e.extract(VIDEO_A)).toBeNull();
    });

    it('handles Whisper throwing gracefully (returns null)', async () => {
      // Arrange
      const whisper: WhisperLike = {
        extract: vi.fn().mockRejectedValue(new Error('Whisper failed')),
      };
      const e = new TranscriptExtractor({
        whisperExtractor: whisper,
        rateLimitDelay: 10,
      });
      mockFetchTranscript.mockRejectedValue(new Error('No transcript'));

      // Act + Assert
      expect(await e.extract(VIDEO_A)).toBeNull();
    });

    it('skips Whisper when useWhisperFallback=false', async () => {
      // Arrange
      const whisper: WhisperLike = { extract: vi.fn() };
      const e = new TranscriptExtractor({
        whisperExtractor: whisper,
        rateLimitDelay: 10,
      });
      mockFetchTranscript.mockRejectedValue(new Error('No transcript'));

      // Act
      const result = await e.extract(VIDEO_A, 3, false);

      // Assert
      expect(result).toBeNull();
      expect(whisper.extract).not.toHaveBeenCalled();
    });
  });

  describe('extractBatch', () => {
    it('extracts transcripts for multiple videos', async () => {
      // Arrange
      mockFetchTranscript.mockResolvedValue([{ offset: 0, duration: 1000, text: 'Test' }]);

      // Act
      const results = await extractor.extractBatch([VIDEO_A, VIDEO_B]);

      // Assert
      expect(Object.keys(results)).toHaveLength(2);
      expect(results.dQw4w9WgXcQ).not.toBeNull();
      expect(results.jNQXAC9IVRw).not.toBeNull();
    });

    it('isolates failures per video', async () => {
      // Arrange
      let n = 0;
      mockFetchTranscript.mockImplementation(() => {
        n++;
        if (n === 1) {
          return Promise.resolve([{ offset: 0, duration: 1000, text: 'OK' }]);
        }
        return Promise.reject(new Error('Failed'));
      });

      // Act
      const results = await extractor.extractBatch([VIDEO_A, VIDEO_B]);

      // Assert
      expect(results.dQw4w9WgXcQ).not.toBeNull();
      expect(results.jNQXAC9IVRw).toBeNull();
    });

    it('throws ValidationError on non-array input', async () => {
      // Arrange — deliberately shape-broken
      const bad = 'not-array' as unknown as VideoId[];
      // Act + Assert
      await expect(extractor.extractBatch(bad)).rejects.toThrow(ValidationError);
    });
  });

  describe('formatTranscriptWithTimestamps', () => {
    it('formats segments with MM:SS timestamps', () => {
      // Arrange + Act
      const formatted = extractor.formatTranscriptWithTimestamps({
        full_text: 'Hello world',
        segments: [
          { start: 0, duration: 2, text: 'Hello world' },
          { start: 2, duration: 3, text: 'Test text' },
        ],
        language: 'en',
        is_auto_generated: true,
      });
      // Assert
      expect(formatted).toContain('[00:00] Hello world');
      expect(formatted).toContain('[00:02] Test text');
    });

    it('uses HH:MM:SS once the offset exceeds one hour', () => {
      // Arrange + Act
      const formatted = extractor.formatTranscriptWithTimestamps({
        full_text: 'Long',
        segments: [{ start: 3661, duration: 1, text: 'One hour in' }],
        language: 'en',
        is_auto_generated: true,
      });
      // Assert
      expect(formatted).toContain('[01:01:01]');
    });

    it('returns empty string when given null', () => {
      // Arrange + Act + Assert
      expect(extractor.formatTranscriptWithTimestamps(null)).toBe('');
    });
  });

  describe('generateYouTubeTimestampUrl', () => {
    it('builds a URL with the integer seconds parameter', () => {
      // Arrange + Act
      const url = extractor.generateYouTubeTimestampUrl('dQw4w9WgXcQ', 42);
      // Assert
      expect(url).toBe('https://youtube.com/watch?v=dQw4w9WgXcQ&t=42s');
    });

    it('floors fractional seconds', () => {
      // Arrange + Act
      const url = extractor.generateYouTubeTimestampUrl('dQw4w9WgXcQ', 42.7);
      // Assert
      expect(url).toBe('https://youtube.com/watch?v=dQw4w9WgXcQ&t=42s');
    });
  });

  describe('getTranscriptStats', () => {
    it('computes word, character, segment, and duration stats', () => {
      // Arrange + Act
      const stats = extractor.getTranscriptStats({
        full_text: 'Hello world this is a test',
        segments: [
          { start: 0, duration: 2, text: 'Hello world' },
          { start: 2, duration: 3, text: 'this is a test' },
        ],
        language: 'en',
        is_auto_generated: true,
      });
      // Assert
      expect(stats.word_count).toBe(6);
      expect(stats.char_count).toBe(26);
      expect(stats.segment_count).toBe(2);
      expect(stats.duration_seconds).toBe(5);
      expect(stats.language).toBe('en');
      expect(stats.is_auto_generated).toBe(true);
    });

    it('returns zero stats and unknown language when given null', () => {
      // Arrange + Act
      const stats = extractor.getTranscriptStats(null);
      // Assert
      expect(stats.word_count).toBe(0);
      expect(stats.language).toBe('unknown');
      expect(stats.is_auto_generated).toBe(true);
    });

    it('returns zero stats for an empty-segments transcript', () => {
      // Arrange + Act
      const stats = extractor.getTranscriptStats({
        full_text: '',
        segments: [],
        language: 'en',
        is_auto_generated: false,
      });
      // Assert
      expect(stats.word_count).toBe(0);
      expect(stats.segment_count).toBe(0);
      expect(stats.duration_seconds).toBe(0);
    });
  });
});
