/**
 * TranscriptRepository tests — Phase 2 Wave 2.
 *
 * Exercises the repository against `:memory:` SQLite with the real
 * `DatabaseManager`, real DDL, real foreign keys, real transactions. No
 * mocks. AAA pattern throughout.
 *
 * The non-negotiable test in this file is the atomicity check at the bottom
 * of the `upsert` block: a throw between the DELETE and the INSERT must
 * leave the pre-existing row intact. v1's TS implementation issued the two
 * statements outside any transaction, which made this scenario silently
 * destroy data. The audit (`docs/REWRITE_AUDIT.md`) flagged this as the
 * canonical example of the "transaction() exists but unused" class of bug.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { DatabaseManager } from '../database/connection.js';
import {
  TranscriptRepository,
  type TranscriptInput,
} from '../database/TranscriptRepository.js';
import { DatabaseError } from '../errors/index.js';
import { asVideoId, type VideoId } from '../types/branded.js';

/**
 * Insert a parent `videos` row so transcript FK references succeed. Returns
 * the branded id so each test pins the same value through its arrange/act.
 *
 * Kept as a free function (not a `beforeEach`) so each test composes its
 * own arrangement explicitly — the AAA convention for this file is to keep
 * setup visible in the test body.
 */
function insertParentVideo(dbm: DatabaseManager, raw: string): VideoId {
  const vid = asVideoId(raw);
  dbm.withTransaction((db) => {
    db.prepare(
      `INSERT INTO videos (video_id, title, channel_id, channel_title, published_at, duration, duration_seconds, is_short)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(vid, 'test video', 'UCxxxx', 'channel', '2024-01-01T00:00:00Z', 'PT1M', 60, 0);
  });
  return vid;
}

describe('TranscriptRepository.upsert', () => {
  let dbm: DatabaseManager;
  let repo: TranscriptRepository;

  beforeEach(() => {
    dbm = new DatabaseManager(':memory:');
    repo = new TranscriptRepository(dbm);
  });

  afterEach(() => {
    dbm.close();
  });

  it('inserts a new transcript when none exists for the video', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    const input: TranscriptInput = {
      language: 'en',
      fullText: 'hello world',
      segments: [{ text: 'hello world', start: 0, duration: 1 }],
      isAutoGenerated: true,
    };

    // Act
    const inserted = repo.upsert(vid, input);

    // Assert
    expect(inserted.video_id).toBe(vid);
    expect(inserted.language).toBe('en');
    expect(inserted.full_text).toBe('hello world');
    expect(inserted.is_auto_generated).toBe(1);
    expect(inserted.segments_json).toBe(
      JSON.stringify([{ text: 'hello world', start: 0, duration: 1 }])
    );
  });

  it('replaces an existing transcript for the same video', () => {
    // Arrange — first upsert lands an "original" row
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    repo.upsert(vid, { fullText: 'original' });

    // Act — second upsert replaces it
    const replaced = repo.upsert(vid, {
      language: 'fr',
      fullText: 'remplacé',
      isAutoGenerated: false,
    });

    // Assert — only ONE row remains, and it carries the new payload
    expect(replaced.full_text).toBe('remplacé');
    expect(replaced.language).toBe('fr');
    expect(replaced.is_auto_generated).toBe(0);

    const count = dbm
      .prepare<readonly [], { c: number }>(
        'SELECT COUNT(*) AS c FROM transcripts WHERE video_id = ?'
      )
      .get(vid);
    expect(count?.c).toBe(1);
  });

  it("defaults language to 'en' and segments_json to '[]' when omitted", () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');

    // Act
    const inserted = repo.upsert(vid, { fullText: 'no extras' });

    // Assert
    expect(inserted.language).toBe('en');
    expect(inserted.segments_json).toBe('[]');
    expect(inserted.is_auto_generated).toBe(1); // default true -> 1
  });

  it('stores is_auto_generated=0 when input flag is explicitly false', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');

    // Act
    const inserted = repo.upsert(vid, {
      fullText: 'manual captions',
      isAutoGenerated: false,
    });

    // Assert
    expect(inserted.is_auto_generated).toBe(0);
  });

  /**
   * THE ATOMICITY TEST — non-negotiable per the v2 audit.
   *
   * Strategy: force the INSERT half of the upsert to fail (via a NOT NULL
   * constraint violation on `full_text`) so that the upsert's transaction
   * throws AFTER the DELETE has executed but BEFORE the INSERT commits.
   * If `withTransaction` is wired correctly, the DELETE rolls back with
   * the failed INSERT — meaning the original row survives.
   *
   * In v1's broken implementation, the DELETE would have already committed
   * and the original row would be GONE.
   */
  it('rolls back the DELETE when the INSERT fails (atomicity)', () => {
    // Arrange — original row to defend
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    const original = repo.upsert(vid, {
      language: 'en',
      fullText: 'ORIGINAL — must survive a failed upsert',
      isAutoGenerated: true,
    });
    expect(original.full_text).toBe('ORIGINAL — must survive a failed upsert');

    // Act — second upsert with a NULL fullText. SQLite's NOT NULL
    // constraint on `full_text` rejects the INSERT, but only AFTER the
    // DELETE has already run inside the same transaction. The cast is
    // confined to this test (forcing a runtime-only violation).
    const badInput = {
      language: 'fr',
      fullText: null as unknown as string,
      isAutoGenerated: false,
    } as TranscriptInput;

    expect(() => repo.upsert(vid, badInput)).toThrow(DatabaseError);

    // Assert — the original row is still present, unchanged. If the
    // DELETE had committed independently of the failed INSERT, this
    // assertion would fail with `surviving === undefined`.
    const surviving = repo.findByVideoId(vid);
    expect(surviving).toBeDefined();
    expect(surviving?.full_text).toBe('ORIGINAL — must survive a failed upsert');
    expect(surviving?.language).toBe('en');
    expect(surviving?.is_auto_generated).toBe(1);
  });

  it('wraps non-DatabaseError causes in DatabaseError', () => {
    // Arrange — no parent `videos` row, so the FK on `transcripts.video_id`
    // rejects the insert. The repository catches the bare SQLite error and
    // wraps it.
    const orphanId = asVideoId('aaaaaaaaaaa');

    // Act + Assert
    expect(() => repo.upsert(orphanId, { fullText: 'no parent' })).toThrow(
      DatabaseError
    );
  });
});

describe('TranscriptRepository.findByVideoId', () => {
  let dbm: DatabaseManager;
  let repo: TranscriptRepository;

  beforeEach(() => {
    dbm = new DatabaseManager(':memory:');
    repo = new TranscriptRepository(dbm);
  });

  afterEach(() => {
    dbm.close();
  });

  it('returns the persisted row parsed through TranscriptRowSchema', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    repo.upsert(vid, { fullText: 'findable' });

    // Act
    const found = repo.findByVideoId(vid);

    // Assert
    expect(found).toBeDefined();
    expect(found?.video_id).toBe(vid);
    expect(found?.full_text).toBe('findable');
    expect(typeof found?.extracted_at).toBe('string'); // CURRENT_TIMESTAMP populated
  });

  it('returns undefined when no transcript exists for the video', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');

    // Act
    const found = repo.findByVideoId(vid);

    // Assert
    expect(found).toBeUndefined();
  });
});

describe('TranscriptRepository.exists', () => {
  let dbm: DatabaseManager;
  let repo: TranscriptRepository;

  beforeEach(() => {
    dbm = new DatabaseManager(':memory:');
    repo = new TranscriptRepository(dbm);
  });

  afterEach(() => {
    dbm.close();
  });

  it('returns false before any transcript has been inserted', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');

    // Act + Assert
    expect(repo.exists(vid)).toBe(false);
  });

  it('returns true after a transcript has been inserted', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    repo.upsert(vid, { fullText: 'present' });

    // Act + Assert
    expect(repo.exists(vid)).toBe(true);
  });
});

describe('TranscriptRepository.deleteByVideoId', () => {
  let dbm: DatabaseManager;
  let repo: TranscriptRepository;

  beforeEach(() => {
    dbm = new DatabaseManager(':memory:');
    repo = new TranscriptRepository(dbm);
  });

  afterEach(() => {
    dbm.close();
  });

  it('removes the row and returns 1 when a transcript exists', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    repo.upsert(vid, { fullText: 'about to be deleted' });

    // Act
    const changes = repo.deleteByVideoId(vid);

    // Assert
    expect(changes).toBe(1);
    expect(repo.exists(vid)).toBe(false);
  });

  it('returns 0 when no transcript exists (idempotent)', () => {
    // Arrange
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');

    // Act
    const changes = repo.deleteByVideoId(vid);

    // Assert
    expect(changes).toBe(0);
  });
});

describe('TranscriptRepository.count', () => {
  let dbm: DatabaseManager;
  let repo: TranscriptRepository;

  beforeEach(() => {
    dbm = new DatabaseManager(':memory:');
    repo = new TranscriptRepository(dbm);
  });

  afterEach(() => {
    dbm.close();
  });

  it('returns 0 on an empty table', () => {
    // Act + Assert
    expect(repo.count()).toBe(0);
  });

  it('returns the total number of transcript rows across videos', () => {
    // Arrange — three videos, each with a transcript
    const ids = ['dQw4w9WgXcQ', 'oHg5SJYRHA0', 'kJQP7kiw5Fk'];
    for (const raw of ids) {
      const vid = insertParentVideo(dbm, raw);
      repo.upsert(vid, { fullText: `transcript for ${raw}` });
    }

    // Act
    const total = repo.count();

    // Assert
    expect(total).toBe(3);
  });
});

describe('TranscriptRepository — fail-after-close discipline', () => {
  it('throws DatabaseError when called after the manager is closed', () => {
    // Arrange
    const dbm = new DatabaseManager(':memory:');
    const repo = new TranscriptRepository(dbm);
    const vid = insertParentVideo(dbm, 'dQw4w9WgXcQ');
    dbm.close();

    // Act + Assert
    expect(() => repo.findByVideoId(vid)).toThrow(DatabaseError);
    expect(() => repo.exists(vid)).toThrow(DatabaseError);
    expect(() => repo.count()).toThrow(DatabaseError);
    expect(() => repo.deleteByVideoId(vid)).toThrow(DatabaseError);
    expect(() => repo.upsert(vid, { fullText: 'x' })).toThrow(DatabaseError);
  });
});
